version: '4'
services:

  api:
      image : 'mouadl342/vcm'
      container_name : 'api'
      ports :
        - 80:5002
      depends_on :
        - rabbitmq
      environment:
        BUCKET: ${BUCKET}
        AWS_SECRET_KEY: ${AWS_SECRET_KEY}
        AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
        ROUTE53_HOSTED_ZONE_ID: ${ROUTE53_HOSTED_ZONE_ID}
        domain: ${domain}
        MONGO_URL: ${MONGO_URL}
      networks:
        - goto
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'queue'
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: pass
    networks:
        - goto
networks :
  goto :
    driver : bridge
      
